// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deletehub.sql

package db

import (
	"context"
)

const deleteHub = `-- name: DeleteHub :exec
DELETE FROM hubs
WHERE hubs.id = ?
`

func (q *Queries) DeleteHub(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHub, id)
	return err
}
