// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gethub.sql

package db

import (
	"context"
)

const getHub = `-- name: GetHub :one
SELECT id, name, description, active, owner_id, save_messages, created_at, updated_at
FROM hubs
WHERE hubs.id = ?
`

func (q *Queries) GetHub(ctx context.Context, id string) (Hub, error) {
	row := q.db.QueryRowContext(ctx, getHub, id)
	var i Hub
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.OwnerID,
		&i.SaveMessages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
