// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Hub struct {
	ID           string
	Name         string
	Description  sql.NullString
	Active       bool
	OwnerID      string
	SaveMessages bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID             string
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
