// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: newhub.sql

package db

import (
	"context"
)

const createHub = `-- name: CreateHub :exec
INSERT INTO hubs (id, name, owner_id)
VALUES (?, ?, ?)
`

type CreateHubParams struct {
	ID      string
	Name    string
	OwnerID string
}

func (q *Queries) CreateHub(ctx context.Context, arg CreateHubParams) error {
	_, err := q.db.ExecContext(ctx, createHub, arg.ID, arg.Name, arg.OwnerID)
	return err
}
