// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateroominfo.sql

package db

import (
	"context"
	"database/sql"
)

const updateRooms = `-- name: UpdateRooms :exec

UPDATE hubs
SET name = ?, description = ?, save_messages = ?
WHERE id = ?
`

type UpdateRoomsParams struct {
	Name         string
	Description  sql.NullString
	SaveMessages bool
	ID           string
}

func (q *Queries) UpdateRooms(ctx context.Context, arg UpdateRoomsParams) error {
	_, err := q.db.ExecContext(ctx, updateRooms,
		arg.Name,
		arg.Description,
		arg.SaveMessages,
		arg.ID,
	)
	return err
}
