// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateroomactive.sql

package db

import (
	"context"
)

const updateRoomActive = `-- name: UpdateRoomActive :exec

UPDATE hubs
SET active = ?
WHERE hubs.id = ?
`

type UpdateRoomActiveParams struct {
	Active bool
	ID     string
}

func (q *Queries) UpdateRoomActive(ctx context.Context, arg UpdateRoomActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomActive, arg.Active, arg.ID)
	return err
}
